### ISSUE TITLE
运行./manage.py runserver报错，且打不开网页，求解

### ISSUE THREAD

**Issue by ipgtzuo** [vicalloy/lbforum-site#2]
**(env) MacBook-Pro:lbforum-site** ****$ ./manage.py runserver
Performing system checks...

System check identified some issues:

**WARNINGS:**
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.

**System check identified 1 issue (0 silenced).**
June 21, 2017 - 15:51:45
Django version 1.10, using settings 'lbforum_site.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
U```
nhandled exception in thread started by <function wrapper at 0x10daf6398>
Traceback (most recent call last):
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 142, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 49, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/lbforum_site/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/Users/g.t.zuo/Documents/GitHub/lbforum-site/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes exactly 1 argument (2 given)
```

**Comment by vicalloy** [comment]
django_debug_toolbar 的版本太低了。
requirments.txt已经更新。
将相关依赖升级一下就可以了。

**Comment by ipgtzuo** [comment]
确实搞定了，另外在执行$mg bower install 也会报错，把django-bower改成5.2.0才可以
